### ISSUE TITLE
Unsupported operand types

### ISSUE THREAD

**Issue by fyher** [KleeGroup/Recaptcha-bundle-symfony#1]
line 71  kleegroup/google-recaptcha-bundle/RequestMethod/CurlPost.php 

$this->curl->setoptArray($handle, $options + $this->options);

 i have PHP 7.0.25-1~dotdeb+8.1 
do you have the idea  ? 

thanks

**Comment by t-veron** [comment]
The operator "+" is supported by PHP.
For better compatibility we have replaced it by array_replace in version 1.0.1
